server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:e:/upload/
mybatis:
  type-aliases-package: com.hansheng.springboot.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
   com.hansheng.springboot.mapper: debug
fdfs:
  tracker-list:
    - 192.168.131.129:22122
  connect-timeout: 600
  so-timeout: 1500
  thumb-image:
    height: 200
    width: 200